#!/bin/bash

/usr/sbin/nginx -c /etc/nginx/nginx.conf

mount --bind /root/disk /mnt/disk

/root/Xware/portal

pid=
trap '[[ $pid ]] && kill $pid; /root/Xware/portal -s; exit 0' SIGINT SIGTERM
while :
do 
	sleep 60 & pid=$!
	wait
	pid=

	ps -ef | grep ETMDaemon | grep -v grep > /dev/null
	if [ $? -ne 0 ]
	then
		/root/Xware/portal
	fi
done

