#!/bin/bash

/usr/sbin/nginx -c /etc/nginx/nginx.conf

/Xware/portal

pid=
trap '[[ $pid ]] && kill $pid; /Xware/portal -s; exit 0' SIGINT SIGTERM
while :
do 
	sleep 60 & pid=$!
	wait
	pid=

	ps -ef | grep ETMDaemon | grep -v grep > /dev/null
	if [ $? -ne 0 ]
	then
		/Xware/portal
	fi
done

